.TH NOCTVM 1 "June 2025" "NoctVM Project" "User Commands"
.SH NAME
noctvm \- execute and test NoctVM projects

.SH SYNOPSIS
.B noctvm
[\fIOPTIONS\fR] [\fIFILE\fR]

.SH DESCRIPTION
\fBnoctvm\fR is a command-line tool for running projects developed with NoctVM.  
It executes a source file in the current directory.

This tool is intended for use in development and distribution workflows.  
It provides lightweight runtime support for projects written in \fBNoctLang\fR.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display usage information and exit.

.TP
.B \-v, \-\-version
Show version details and exit.

.SH EXAMPLES
.TP
Run the default NoctVM project in the current directory:
.B
noctvm

.SH SEE ALSO
.BR noct (1)

.SH AUTHOR
Written by Awe Morris.

.SH COPYRIGHT
Copyright © 2025 Awe Morris.  
This is free software; see the source for copying conditions.  
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
