/* XPM */
char *icon_xpm[] = {
"32 32 8 1 ",
"  c black",
". c #281864",
"X c #845778",
"o c #0D438C",
"O c #47409B",
"+ c #5F85D3",
"@ c #EDAAAE",
"# c white",
"oooooooooOooO+######ooooooooo.oo",
"ooooooooo.o++oOOOOOO##oooooooooo",
"oooooooO.#oOOO+OO..OO.###Ooooooo",
"oooooooo . @@oOOOOO+OOO+@ooooo#o",
"ooooooo    .OO##+OOOOo#..oooo.oo",
"ooooooo . OO#X@@@O+O##@@Oooooooo",
"ooooooo. o+@X@#@@@+#@@#@@ooo.ooo",
"oooooo o.O+@@###@@@# ####.oooooo",
"oooooo  .++#XO###X@#.## #oooooo#",
"oooooo X.O@##. X ## X  ###oooooo",
"ooo.oo. .O@@@#@@## ##@####oooooo",
"oooooo .X.+@##@##@ . ###o#oooooo",
"oooooo. . X.@##@#..  ##X#.oo.ooo",
"oooooo . o ...OOO@#O@+o.#ooooooo",
"oooooX+. O.    ....@...@#.oooooo",
"oooo .....O+.+..+OO.OO@@#@oooooo",
"oooo     .. .@###@@O@@@###.ooooo",
"ooo+ +....o ++X#@#########oooooo",
".oo O OO..X.++@@@@@@##@#@#.ooooo",
"ooo +  O....+@+@@####@@@@##+Oooo",
"Ooo. .  . . +XOX@@@@@@@@#@#oo.oo",
"oo.       + +XO++OX.@O@@@@oOoooo",
"oo .+ X.+ ..o.+@+@@@+@@XO@oooO.o",
"oo.  . . +.++.++@O++@O++O@oooooo",
"oooXo  . o oO.+++++O++++.@oooooo",
"ooo.  O   .+.OO++OO+O+OO.ooooooo",
"oo+  .  . .o.oOoOO+.O.O.#ooooooo",
"ooX  X.. O...OOOOOOO.O...o##X.##",
"ooo O....O.......O.... O@X@#@ ##",
"ooooo + O.  .....  .X@XX@X@X.X@X",
"oooo  + .    XX .  .@X    ##@#O@",
"oooo. o.O. XXXX@ .X X X.@  XOOO."
};

